### ISSUE TITLE
Cannot read property 'getIdentity' of undefined",

### ISSUE THREAD

**Issue by dinghu** [ProChain/pra_scatter_middleware#10]
Cannot read property 'getIdentity' of undefined",

**Comment by oday0311** [comment]
which url are you testing.

**Comment by dinghu** [comment]
> which url are you testing.

https://chain.pro/candybox/#/candybox

**Comment by oday0311** [comment]
make sure you follow the webview's sample, most of the time it is the js not loaded , or the webview's  config is not well..
