### ISSUE TITLE
When will you open the source code of pra_middleware.js ?

### ISSUE THREAD

**Issue by vjoke** [ProChain/pra_scatter_middleware#3]
First, it's awesome. However, people will have risk to use such middleware for their projects, especially for  cryptocurrency. Hope to see it open source.

**Comment by oday0311** [comment]
well, we will open the code soon

**Comment by heyconnor** [comment]
确实是这样，不开源一是不放心用，二是没法修改

**Comment by vjoke** [comment]
Prabox 目前只支持transfer action， 其他的都报错吗？

**Comment by oday0311** [comment]
已经都支持了， middle ware实际上做的是一个事件转发， 支持部分的逻辑实现是在native钱包里的，
