### ISSUE TITLE
安卓设备在使用案例文件的时候有报错，文件不全

### ISSUE THREAD

**Issue by Hansong9527** [ProChain/pra_scatter_middleware#8]
我尝试在自己的应用里面使用对应的js文件和先夹在dapp的页面，后面再注入对应的js，但是在实际操作中发现demo的dapp并没有识别到scatter对象，无法进行调用。请问有完整的案例代码么，包括完整的安卓文件。

**Comment by oday0311** [comment]
目前暂时还没有开源完整的android项目， 但是项目中的android webview基本上是我们自用的webview删掉一下钱包基础功能的代码了， https://chain.pro/candybox/#/candybox， 可以用这个测试，
